import fs from "node:fs";
import path from "node:path";
import type { PlatformSettings, PlatformStatus } from "@agentstore/shared";
import {
  applyPlatformEnv,
  checkAgentSandboxController,
  isAapConfigured,
  isOpenshiftConfigured,
  listAgentDeployments,
  listCredentialsByKind,
  listExecutionEnvironments,
  listJobTemplates,
  listOrganizations,
  listProjects,
  listRecentJobs,
  pingAap,
  pingOpenshift,
} from "@agentstore/engine-ansible";
import { applyOpenShellServiceEnv, isOpenShellServiceConfigured, pingOpenShellService } from "@agentstore/engine-openshell";
// Note: deliberately calling checkAgentSandboxController() directly from
// @agentstore/engine-ansible here, not the checkAgentSandboxStatus()
// wrapper in ./agentSandbox — that module needs to import
// getPlatformSettings/savePlatformSettings/ensurePlatformEnv from *this*
// file for the "Install Agent Sandbox Service" build+deploy flow, and a
// platform.ts <-> agentSandbox.ts circular import is easy to get wrong
// silently (works until it doesn't, depending on evaluation order).
// One-directional (agentSandbox.ts -> platform.ts) avoids that entirely.

const DEFAULT_SETTINGS: PlatformSettings = {
  aapControllerUrl: "",
  aapJobTemplateId: "",
  aapConsoleUrl: "",
  aapInsecureTls: true,
  openshiftApiUrl: "",
  openshiftNamespace: "agent-workloads",
  openshiftConsoleUrl: "",
  openshiftInsecureTls: true,
  openshellServiceUrl: "",
  // Real, published chart — see docs.nvidia.com/openshell/kubernetes/openshift.
  // Left editable for a private mirror or pinned dev build.
  openshellGatewayChartRef: "oci://ghcr.io/nvidia/openshell/helm-chart",
  openshellGatewayChartVersion: "",
  openshellGatewayNamespace: "openshell",
  openshellGatewayWorkloadKind: "statefulset",
  openshellGatewayJobTemplateId: "",
  aapOrganizationName: "Default",
  aapProjectName: "AgentStore",
  aapProjectGitUrl: "",
  aapProjectGitBranch: "main",
  aapProjectScmCredentialId: "",
  aapExecutionEnvironmentId: "",
};

function dataDir(): string {
  if (process.env.SECRETS_DATA_DIR) return process.env.SECRETS_DATA_DIR;
  const candidates = [
    path.resolve(process.cwd(), ".data"),
    path.resolve(process.cwd(), "../../.data"),
    path.resolve(__dirname, "../../../../.data"),
  ];
  return candidates.find((dir) => fs.existsSync(dir)) ?? candidates[0];
}

function settingsPath(): string {
  return path.join(dataDir(), "platform.json");
}

function loadFromDisk(): PlatformSettings {
  const file = settingsPath();
  if (!fs.existsSync(file)) return { ...DEFAULT_SETTINGS };
  try {
    const raw = JSON.parse(fs.readFileSync(file, "utf8")) as Partial<PlatformSettings>;
    return { ...DEFAULT_SETTINGS, ...raw };
  } catch {
    return { ...DEFAULT_SETTINGS };
  }
}

let cached: PlatformSettings | null = null;

export function getPlatformSettings(): PlatformSettings {
  if (!cached) cached = loadFromDisk();
  return cached;
}

export function savePlatformSettings(patch: Partial<PlatformSettings>): PlatformSettings {
  const next: PlatformSettings = { ...getPlatformSettings(), ...patch };
  if (next.openshiftNamespace.trim() === "") next.openshiftNamespace = "agent-workloads";
  if (next.openshellGatewayNamespace.trim() === "") next.openshellGatewayNamespace = "openshell";
  const dir = dataDir();
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(settingsPath(), JSON.stringify(next, null, 2));
  cached = next;
  applyPlatformEnv(next);
  applyOpenShellServiceEnv(next);
  return next;
}

export function ensurePlatformEnv(): void {
  const settings = getPlatformSettings();
  applyPlatformEnv(settings);
  applyOpenShellServiceEnv(settings);
}

/** Clears all cluster-specific state (deploy statuses, build results,
 *  image references, AAP IDs) while keeping connection URLs and config
 *  that the admin has already updated for the new cluster. */
export function resetClusterState(): PlatformSettings {
  return savePlatformSettings({
    // AAP IDs — will be regenerated by "Create job templates"
    aapJobTemplateId: "",
    openshellGatewayJobTemplateId: "",
    aapExecutionEnvironmentId: "",
    // Image refs from old cluster's internal registry
    agentRuntimeImage: undefined,
    // Deploy / build status blobs
    agentstoreDeploy: undefined,
    rhdhDeploy: undefined,
    eeBuild: undefined,
    agentRuntimeBuild: undefined,
    agentSandboxServiceInstall: undefined,
    aapBootstrap: undefined,
    openshellGatewayDeployment: undefined,
    // Sync token — will be regenerated on next deploy
    syncToken: undefined,
    // OpenShell service URL — old cluster route
    openshellServiceUrl: "",
  });
}

function emptyAapLists(): Pick<
  PlatformStatus["aap"],
  "jobTemplates" | "recentJobs" | "executionEnvironments" | "credentials" | "organizations" | "projects" | "registryCredentials"
> {
  return {
    jobTemplates: [],
    recentJobs: [],
    executionEnvironments: [],
    credentials: [],
    organizations: [],
    projects: [],
    registryCredentials: [],
  };
}

async function probeAap(): Promise<PlatformStatus["aap"]> {
  const configured = isAapConfigured();
  if (!configured) {
    return { configured: false, connected: false, error: "Not configured", ...emptyAapLists() };
  }
  const ping = await pingAap();
  if (!ping.ok) {
    return { configured: true, connected: false, error: ping.error, ...emptyAapLists() };
  }
  try {
    // executionEnvironments/credentials/organizations/projects/
    // registryCredentials feed the "AAP Job Templates" bootstrap card's
    // dropdowns; failures there shouldn't be fatal to the rest of this
    // probe (e.g. an AAP install with one of these endpoints disabled),
    // so each independently falls back to an empty list.
    const [jobTemplates, recentJobs, executionEnvironments, credentials, organizations, projects, registryCredentials] =
      await Promise.all([
        listJobTemplates(),
        listRecentJobs(12),
        listExecutionEnvironments().catch(() => []),
        listCredentialsByKind("scm").catch(() => []),
        listOrganizations().catch(() => []),
        listProjects().catch(() => []),
        listCredentialsByKind("registry").catch(() => []),
      ]);
    return {
      configured: true,
      connected: true,
      jobTemplates,
      recentJobs,
      executionEnvironments,
      credentials,
      organizations,
      projects,
      registryCredentials,
    };
  } catch (err) {
    return {
      configured: true,
      connected: false,
      error: err instanceof Error ? err.message : String(err),
      ...emptyAapLists(),
    };
  }
}

async function probeOpenshift(): Promise<PlatformStatus["openshift"]> {
  const configured = isOpenshiftConfigured();
  if (!configured) {
    return {
      configured: false,
      connected: false,
      error: "Not configured",
      deployments: [],
      agentSandboxController: { installed: false, error: "Not configured" },
    };
  }
  const ping = await pingOpenshift();
  if (!ping.ok) {
    return {
      configured: true,
      connected: false,
      error: ping.error,
      deployments: [],
      agentSandboxController: { installed: false, error: ping.error },
    };
  }
  try {
    // agentSandboxController is its own live check (a separate
    // low-privilege GET /apis) rather than piggybacking on the
    // deployments listing above — it needs to keep reporting a real
    // installed/missing status even if listAgentDeployments() itself
    // fails below (e.g. the configured token can list API groups but
    // not this namespace's Deployments).
    const [deployments, agentSandboxController] = await Promise.all([
      listAgentDeployments(),
      checkAgentSandboxController(),
    ]);
    return { configured: true, connected: true, deployments, agentSandboxController };
  } catch (err) {
    return {
      configured: true,
      connected: false,
      error: err instanceof Error ? err.message : String(err),
      deployments: [],
      agentSandboxController: await checkAgentSandboxController(),
    };
  }
}

async function probeOpenshell(): Promise<PlatformStatus["openshellService"]> {
  const configured = isOpenShellServiceConfigured();
  if (!configured) {
    return { configured: false, connected: false, error: "Not configured" };
  }
  const ping = await pingOpenShellService();
  return { configured: true, connected: ping.ok, error: ping.ok ? undefined : ping.error };
}

export async function getPlatformStatus(): Promise<PlatformStatus> {
  ensurePlatformEnv();
  const [aap, openshift, openshellService] = await Promise.all([
    probeAap(),
    probeOpenshift(),
    probeOpenshell(),
  ]);
  return { settings: getPlatformSettings(), aap, openshift, openshellService };
}

export type PlatformTestTarget = "aap" | "openshift";

export async function testPlatformTarget(target: PlatformTestTarget): Promise<{
  settings: PlatformStatus["settings"];
  aap?: PlatformStatus["aap"];
  openshift?: PlatformStatus["openshift"];
}> {
  ensurePlatformEnv();
  const settings = getPlatformSettings();
  if (target === "aap") return { settings, aap: await probeAap() };
  return { settings, openshift: await probeOpenshift() };
}
