apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: agent-store
spec:
  to:
    kind: Service
    name: agent-store
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
